import { AuthProvider } from "@/components/auth/AuthProvider";
import { GlobalErrorHandler } from "@/components/GlobalErrorHandler";
import { ToasterProvider } from "@/components/toaster-config";
import { GlobalModalProvider } from "@/lib/modal";
import { ThemeProvider } from "@/lib/theme";
import type { Metadata } from "next";
import { Poppins, Source_Code_Pro } from "next/font/google";
import Script from "next/script";
import "../src/utils/whyDidYouRender";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"]
});

const sourceCodePro = Source_Code_Pro({
  variable: "--font-source-code-pro",
  subsets: ["latin"],
  weight: ["400", "500", "600"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${sourceCodePro.variable} antialiased ui-body`}>
        <Script src="/static/theme-script.js" strategy="beforeInteractive" />
        <ThemeProvider>
          <AuthProvider>
            <main className="w-full">{children}</main>
            <GlobalModalProvider />
            <ToasterProvider />
            <GlobalErrorHandler />
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
