import { AuthProvider } from "@/components/auth/AuthProvider";
import { ToasterProvider } from "@/components/toaster-config";
import { GlobalModalProvider } from "@/lib/modal";
import type { Metadata } from "next";
import "../src/utils/whyDidYouRender";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"]
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"]
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/*<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>*/}
      <body className={`antialiased`}>
        <AuthProvider>
          {children}
          <GlobalModalProvider />
          <ToasterProvider />
        </AuthProvider>
      </body>
    </html>
  );
}
