import { AuthProvider } from "@/components/auth/AuthProvider";
import { ConditionalAuthHeader } from "@/components/layout/ConditionalAuthHeader";
import { ToasterProvider } from "@/components/toaster-config";
import { GlobalModalProvider } from "@/lib/modal";
import { ThemeProvider } from "@/lib/theme";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { headers } from "next/headers";
import Script from "next/script";
import "../src/utils/whyDidYouRender";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"]
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"]
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nonce = (await headers()).get("x-nonce") ?? undefined;

  return (
    <html lang="en" className="dark" data-theme="dark">
      {/*<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>*/}
      <body className={`${poppins.variable} antialiased`}>
        <Script src="/theme-script.js" strategy="beforeInteractive" nonce={nonce} />
        <ThemeProvider>
          <AuthProvider>
            <ConditionalAuthHeader />
            <main className="min-h-screen bg-bg-secondary theme-transition">{children}</main>
            <GlobalModalProvider />
            <ToasterProvider />
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
