leaves = random.randint(40, 100)
tomatoes = random.randint(5, leaves // 5)
croutons = random.randint(tomatoes, tomatoes * 2)
olives = random.randint(1, tomatoes // 2)
make_salad(leaves, tomatoes, croutons, olives)
